[package]
name = "ekubo_sdk_evm_wasm"
version = "0.1.0"
edition = "2021"
license = "LGPL-2.1"
description = "TypeScript/WASM bindings for ekubo_sdk EVM pools"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1"
derive_more.workspace = true
ekubo_sdk = { path = "../..", features = ["serde", "evm"] }
js-sys = "0.3.91"
wasm-bindgen = "0.2"

[dev-dependencies]
wasm-bindgen-test = "0.2"

[lints]
workspace = true
